ALTER TYPE "TipoTrack" ADD VALUE 'ENLACES_EMPALMES';
ALTER TYPE "TipoTrack" ADD VALUE 'HITOS_UOCT';
ALTER TYPE "TipoTrack" ADD VALUE 'SINTONIA_FINA_EIV';
ALTER TYPE "TipoTrack" ADD VALUE 'TRASPASOS_MANTENCION';
